// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofSVgmNDjXzST22iQpW3ud9jxr2E4PeE',
    appId: '1:926261286404:web:b188945dfab01948c2c751',
    messagingSenderId: '926261286404',
    projectId: 'cycle-app-2026',
    authDomain: 'cycle-app-2026.firebaseapp.com',
    storageBucket: 'cycle-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQCEp51o_dQVS4UV2CAJN9Zv_bunYbgY',
    appId: '1:926261286404:android:bbf9625da38285d8c2c751',
    messagingSenderId: '926261286404',
    projectId: 'cycle-app-2026',
    storageBucket: 'cycle-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcU9rRHqwiB9kXlXBYdgh8ydcB0PtWqC4',
    appId: '1:926261286404:ios:e09a5aa87f37bb6bc2c751',
    messagingSenderId: '926261286404',
    projectId: 'cycle-app-2026',
    storageBucket: 'cycle-app-2026.firebasestorage.app',
    iosBundleId: 'com.kanen.biocircle',
  );
}
